### ISSUE TITLE
Debian不能使用ssh登录duo，提示密码不正确

### ISSUE THREAD

**Issue by RedLeaves699** [milkv-duo/duo-buildroot-sdk#31]
使用官方镜像v1.0.5
使用登录命令`ssh root@192.168.42.1`后输入密码milkv后会出现以下提示：

```bash
ssh root@192.168.42.1
root@192.168.42.1's password: 
Permission denied, please try again.
root@192.168.42.1's password: 
Permission denied, please try again.
root@192.168.42.1's password: 
root@192.168.42.1: Permission denied (publickey,password).
```
使用了boradIO扩展版连接网线

本机操作系统信息
```bash
uname -a
Linux debian01 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
```

使用ssh版本
```bash
ssh -V
OpenSSH_9.2p1 Debian-2+deb12u1, OpenSSL 3.0.11 19 Sep 2023
```

这可能是哪里出了问题？求解惑

**Comment by RedLeaves699** [comment]
本机操作系统信息
Linux debian01 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

**Comment by onkoe** [comment]
I fixed this issue for my custom buildroot by mounting the finished image, opening up `/etc/shadow`, making a new password hash with `openssl passwd -1 "milkv"`, and pasting the output hash between the first two colons after `root` in the file. 

On the other hand, you can also use serial to automatically login and change the password. That's [described here!](https://milkv.io/docs/duo/getting-started/setup#serial-console) ☺️

**Comment by lztmfx** [comment]
我在windows10上也是无法通过ssh登录，IP为192.168.42.54，一直报错密码milkv不正确

**Comment by RedLeaves699** [comment]
@onkoe  Thank you for your experience, it really helps.

I login milkv successfully now by serial and change the password of "root". Unfortunately, I still can't login by SSH on my Debian machine. But I login in "root" successfully with SSH on Windows Powershell, which makes me confused...

I checked the version of SSH on duo, it's `Dropbear v2020.81`, while the SSH version on my Debian machine is `OpenSSH_9.2p1 Debian-2+deb12u1, OpenSSL 3.0.11 19 Sep 2023`. Problems may arise here.

**Comment by onkoe** [comment]
Glad it helped! Let’s see if we can get this fixed. 😄

In your `~.ssh/authorized_keys` file, is there an existing entry for the Duo’s IP? If so, try removing it! 

Otherwise, what seems to be the issue? Does it not connect at all, or is the password just not working?

**Comment by RedLeaves699** [comment]
> Glad it helped! Let’s see if we can get this fixed. 😄
> 
> In your `~.ssh/authorized_keys` file, is there an existing entry for the Duo’s IP? If so, try removing it!
> 
> Otherwise, what seems to be the issue? Does it not connect at all, or is the password just not working?

I have removed the authorized_keys. The issue is that the password just not working. Although I input correct password again and again...

**Comment by RedLeaves699** [comment]
I think I found some clues about the problem. I used `ssh -vvv root@192.168.42.1` on my Debian machine and my Windows10 machine, part of the difference of the result  is shown below:

Debian 12 (Can not login duo)
```bash
debug1: Local version string SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u1
debug1: Remote protocol version 2.0, remote software version OpenSSH_9.2p1 Debian-2+deb12u1
```

Windows10 (Successfully login duo)
```bash
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version dropbear_2020.81
```

It seems that `OpenSSH_9.2p1 Debian-2+deb12u1` can't recognise the correct SSH version of milkv-duo.
